### ISSUE TITLE
Error while installing npm packages

### ISSUE THREAD

**Issue by ghost** [Fiddlekins/podbot#24]
```
uws.target.mk:116: recipe for target 'Release/obj.target/uws/src/addon.o' failed
make: *** [Release/obj.target/uws/src/addon.o] Error 1
make: Leaving directory '/home/ubuntu/podbot/node_modules/@discordjs/uws/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-65-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/podbot/node_modules/@discordjs/uws
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @discordjs/uws@11.149.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @discordjs/uws@11.149.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-02-03T00_38_49_888Z-debug.log

```

**Comment by Fiddlekins** [comment]
Install errors aside, I don't believe the bot is functional these days anyway. Discord messed around with the API in the past and I got tired of trying to figure out what the fix was when their documentation was inaccurate.
